import { GoogleGenAI, Type } from "@google/genai"
import PDFDocument from "pdfkit"

const ai = new GoogleGenAI({
    apiKey: process.env.GOOGLE_GENAI_API_KEY
})

const interviewReportSchema = {
    type: Type.OBJECT,
    properties: {
        matchScore: {
            type: Type.NUMBER,
            description: "A score between 0 and 100 indicating how well the candidate's profile matches the job description"
        },
        technicalQuestions: {
            type: Type.ARRAY,
            description: "Technical questions that can be asked in the interview along with their intention and how to answer them",
            items: {
                type: Type.OBJECT,
                properties: {
                    question: { type: Type.STRING, description: "The technical question that can be asked in the interview" },
                    intention: { type: Type.STRING, description: "The intention of interviewer behind asking this question" },
                    answer: { type: Type.STRING, description: "How to answer this question" }
                },
                required: ["question", "intention", "answer"]
            }
        },
        behavioralQuestions: {
            type: Type.ARRAY,
            description: "Behavioral questions that can be asked in the interview along with their intention and how to answer them",
            items: {
                type: Type.OBJECT,
                properties: {
                    question: { type: Type.STRING, description: "The behavioral question that can be asked in the interview" },
                    intention: { type: Type.STRING, description: "The intention of interviewer behind asking this question" },
                    answer: { type: Type.STRING, description: "How to answer this question" }
                },
                required: ["question", "intention", "answer"]
            }
        },
        skillGaps: {
            type: Type.ARRAY,
            description: "List of skill gaps in the candidate's profile along with their severity",
            items: {
                type: Type.OBJECT,
                properties: {
                    skill: { type: Type.STRING, description: "The skill which the candidate is lacking" },
                    severity: { type: Type.STRING, enum: ["low", "medium", "high"], description: "The severity of this skill gap" }
                },
                required: ["skill", "severity"]
            }
        },
        preparationPlan: {
            type: Type.ARRAY,
            description: "A day-wise preparation plan for the candidate",
            items: {
                type: Type.OBJECT,
                properties: {
                    day: { type: Type.NUMBER, description: "The day number, starting from 1" },
                    focus: { type: Type.STRING, description: "The main focus of this day" },
                    tasks: {
                        type: Type.ARRAY,
                        items: { type: Type.STRING },
                        description: "List of tasks to be done on this day"
                    }
                },
                required: ["day", "focus", "tasks"]
            }
        },
        title: {
            type: Type.STRING,
            description: "The title of the job for which the interview report is generated"
        }
    },
    required: ["matchScore", "technicalQuestions", "behavioralQuestions", "skillGaps", "preparationPlan", "title"]
}

async function generateInterviewReport({ resume, selfDescription, jobDescription }) {

    const prompt = `Generate an interview report for a candidate with the following details:
                        Resume: ${resume}
                        Self Description: ${selfDescription}
                        Job Description: ${jobDescription}`

    const response = await ai.models.generateContent({
        model: "gemini-2.5-flash",
        contents: prompt,
        config: {
            responseMimeType: "application/json",
            responseSchema: interviewReportSchema,
        }
    })

    console.log("RAW AI RESPONSE:", response.text)

    return JSON.parse(response.text)
}

/**
 * Schema for the tailored resume content generated by AI
 */
const resumeContentSchema = {
    type: Type.OBJECT,
    properties: {
        name: { type: Type.STRING, description: "Candidate's full name" },
        contact: { type: Type.STRING, description: "Email, phone, location combined in one line" },
        summary: { type: Type.STRING, description: "A tailored 2-3 line professional summary aligned with the job description" },
        skills: {
            type: Type.ARRAY,
            items: { type: Type.STRING },
            description: "Relevant skills tailored to the job description"
        },
        experience: {
            type: Type.ARRAY,
            items: {
                type: Type.OBJECT,
                properties: {
                    title: { type: Type.STRING, description: "Project or role title" },
                    duration: { type: Type.STRING, description: "Duration or dates" },
                    details: {
                        type: Type.ARRAY,
                        items: { type: Type.STRING },
                        description: "Bullet points describing the work done"
                    }
                },
                required: ["title", "details"]
            }
        },
        extras: {
            type: Type.ARRAY,
            items: { type: Type.STRING },
            description: "Extra curricular activities or achievements"
        }
    },
    required: ["name", "contact", "summary", "skills", "experience"]
}

/**
 * Generates a tailored resume (as a PDF buffer) based on the candidate's
 * original resume text, self description and target job description.
 */
async function generateResumePdf({ resume, jobDescription, selfDescription }) {

    const prompt = `Based on the candidate's original resume, self description, and the target job description,
                     create a tailored, professional resume content optimized for this job.
                     Original Resume: ${resume}
                     Self Description: ${selfDescription}
                     Job Description: ${jobDescription}`

    const response = await ai.models.generateContent({
        model: "gemini-2.5-flash",
        contents: prompt,
        config: {
            responseMimeType: "application/json",
            responseSchema: resumeContentSchema,
        }
    })

    const resumeData = JSON.parse(response.text)

    return await buildPdfBuffer(resumeData)
}

/**
 * Builds a PDF buffer from structured resume data using pdfkit
 */
function buildPdfBuffer(resumeData) {
    return new Promise((resolve, reject) => {
        const doc = new PDFDocument({ margin: 50 })
        const buffers = []

        doc.on('data', buffers.push.bind(buffers))
        doc.on('end', () => resolve(Buffer.concat(buffers)))
        doc.on('error', reject)

        // Name
        doc.fontSize(20).font('Helvetica-Bold').text(resumeData.name || "Candidate", { align: 'center' })

        // Contact
        if (resumeData.contact) {
            doc.moveDown(0.3)
            doc.fontSize(10).font('Helvetica').text(resumeData.contact, { align: 'center' })
        }

        doc.moveDown(1)

        // Summary
        if (resumeData.summary) {
            doc.fontSize(13).font('Helvetica-Bold').text('Summary')
            doc.moveDown(0.3)
            doc.fontSize(11).font('Helvetica').text(resumeData.summary)
            doc.moveDown(1)
        }

        // Skills
        if (resumeData.skills?.length) {
            doc.fontSize(13).font('Helvetica-Bold').text('Skills')
            doc.moveDown(0.3)
            doc.fontSize(11).font('Helvetica').text(resumeData.skills.join(' • '))
            doc.moveDown(1)
        }

        // Experience / Projects
        if (resumeData.experience?.length) {
            doc.fontSize(13).font('Helvetica-Bold').text('Experience / Projects')
            doc.moveDown(0.3)

            resumeData.experience.forEach(exp => {
                doc.fontSize(11).font('Helvetica-Bold').text(`${exp.title}${exp.duration ? ' — ' + exp.duration : ''}`)
                exp.details?.forEach(point => {
                    doc.fontSize(10).font('Helvetica').text(`• ${point}`, { indent: 10 })
                })
                doc.moveDown(0.5)
            })
        }

        // Extras
        if (resumeData.extras?.length) {
            doc.fontSize(13).font('Helvetica-Bold').text('Extra Curricular Activities')
            doc.moveDown(0.3)
            resumeData.extras.forEach(item => {
                doc.fontSize(10).font('Helvetica').text(`• ${item}`)
            })
        }

        doc.end()
    })
}

export {
    generateInterviewReport,
    generateResumePdf
}